<?php 
/**
 * ZF2 Buch Kapitel 8
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Pizza
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Name view script
 * 
 * @package    Pizza
 */

// get key
$id = @key($this->pizzaRow);
?>
<div class="hero-unit">
<h1>Hallo Pizza <?php echo $this->escapeHtml($this->pizzaRow[$id]); ?>!</h1>
</div>
<div class="span3">
<p>
<a class="btn btn-primary" href="<?php echo $this->url('pizza'); ?>">
Zurück zur Übersicht
</a>
</p>
</div>
