<?php 
/**
 * ZF2 Buch Kapitel 8
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 8.22 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 8.22</h1>
<h3>Action-Controller mit sauberer Dependency Injection</h3>
<pre>
&lt;?php
namespace Pizza\Controller;

use Pizza\Service\PizzaService;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;

class IndexController extends AbstractActionController
{
    protected $service = null;
    
    public function __construct(PizzaService $service)
    {
        $this->setPizzaService($service);
    }
    
    public function setPizzaService(PizzaService $service)
    {
        $this->service = $service;
    }
    
    public function getPizzaService()
    {
        return $this->service;
    }
    
    public function indexAction()
    {
        $pizzaList = $this->getPizzaService()->fetchList();
        
        return new ViewModel(array(
            'pizzaList' => $pizzaList,
        ));
    }
    
    public function showAction()
    {
        $id = $this->getEvent()->getRouteMatch()->getParam('id');
        
        $pizzaRow = $this->getPizzaService()->fetchSingleById($id);
        
        return new ViewModel(array(
            'pizzaRow' => $pizzaRow,
        ));
    }
}
</pre>
</div>
</div>
