<?php 
/**
 * ZF2 Buch Kapitel 8
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 8.24 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 8.24</h1>
<h3>Erweiterter Model-Service für Einsatz im RESTful-Controller</h3>
<pre>
&lt;?php
namespace Pizza\Service;

use Pizza\Exception\PizzaException;

class PizzaService
{
    protected $pizzaList = array(
        1 => 'Salami', 
        2 => 'Hawaii', 
        3 => 'Melone', 
        4 => 'Schinken', 
        5 => 'Thunfisch',
        6 => 'Speziale', 
        7 => 'Calzone', 
        8 => 'Vierjahreszeiten', 
        9 => 'Spinat',
    );
    
    public function fetchList()
    {
        return $this->pizzaList;
    }
    
    public function fetchSingleById($id = null)
    {
        if (is_null($id)) {
            throw new PizzaException('Pizza ID invalid');
        } elseif (!isset($this->pizzaList[$id])) {
            throw new PizzaException('Pizza not found');
        }

        return array($id => $this->pizzaList[$id]);
    }
    
    public function add($data = null)
    {
        $id = count($this->pizzaList) + 1;
        
        $this->pizzaList[$id] = $data['name'];
        
        return $id;
    }
    
    public function update($id, $data = null)
    {
        $this->pizzaList[$id] = $data['name'];
        
        return $id;
    }
    
    public function delete($id)
    {
        unset($this->pizzaList[$id]);
        
        return true;
    }
}
</pre>
</div>
</div>
