<?php 
/**
 * ZF2 Buch Kapitel 8
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 8.13 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 8.13</h1>
<h3><code>route</code> Event für die Sprachfestlegung nutzen</h3>
<pre>
&lt;?php
namespace Pizza;

use Locale;
use Zend\EventManager\EventInterface;
use Zend\ModuleManager\Feature\BootstrapListenerInterface;
use Zend\Mvc\MvcEvent;

class Module implements BootstrapListenerInterface
{
    public function onBootstrap(EventInterface $e)
    {
        // add language detection
        $eventManager->attach(MvcEvent::EVENT_ROUTE, function ($e) {
            $lang = $e->getRequest()->getQuery('lang', 'de');
            
            Locale::setDefault($lang);
        }, -1000);
    }
}
</pre>
<h3>Ausgabe</h3>
<pre>
<a href="?lang=de">deutsch</a> | <a href="?lang=en">englisch</a> | <a href="?lang=fr">französisch</a>
<?php
    echo 'Locale: ' . Locale::getDefault() . '<br />'; 
    echo 'Aktuelles Datum: ' . $this->dateformat(time(), IntlDateFormatter::LONG) . '<br />'; 
?>
</pre>
</div>
</div>
