<?php 
/**
 * ZF2 Buch Kapitel 8
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 8.15 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 8.15</h1>
<h3>Modul-Klasse registriert <code>LoggingListener</code></h3>
<pre>
&lt;?php
namespace Pizza;

use Pizza\Listener\LoggingListener;
use Zend\EventManager\EventInterface;
use Zend\Log\Logger;
use Zend\Log\Writer\Stream;
use Zend\ModuleManager\Feature\BootstrapListenerInterface;
use Zend\ModuleManager\Feature\ServiceProviderInterface;

class Module implements 
    BootstrapListenerInterface,
    ServiceProviderInterface
{
    public function onBootstrap(EventInterface $e)
    {
        $eventManager = $e->getApplication()->getEventManager();
        $eventManager->attachAggregate(new LoggingListener());
    }

    public function getServiceConfig()
    {
        return array(
            'factories' => array(
                'Pizza\Logging\Service' => function ($serviceManager) {
                    $logFile = LUIGI_ROOT . '/data/log/error.log';
                    
                    $writer = new Stream($logFile);
                    $logger = new Logger();
                    $logger->addWriter($writer);
                    
                    return $logger;
                },
            ),
        );
    }
}
</pre>
</div>
</div>
