<?php 
/**
 * ZF2 Buch Kapitel 8
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 8.32 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 8.32</h1>
<h3>Eigenes Controller-Plugin zum Dumpen von Variablen</h3>
<pre>
&lt;?php
namespace Pizza\Controller\Plugin;

use Zend\Debug\Debug;
use Zend\Mvc\Controller\Plugin\AbstractPlugin;

class Dump extends AbstractPlugin
{
    public function __invoke($data = null, $echo = true)
    {
        return Debug::dump($data, null, $echo);
    }
}
</pre>
</div>
</div>
