<?php 
/**
 * ZF2 Buch Kapitel 8
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 8.30 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 8.30</h1>
<h3>Beispiel für den Einsatz des <code>PostRedirectGet</code> Plugins</h3>
<pre>
&lt;?php
namespace Pizza\Controller;

use Pizza\Service\PizzaService;
use Zend\Http\Response;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;

class IndexController extends AbstractActionController
{
    protected $service = null;
    
    public function __construct(PizzaService $service)
    {
        $this->setPizzaService($service);
    }
    
    public function setPizzaService(PizzaService $service)
    {
        $this->service = $service;
    }
    
    public function getPizzaService()
    {
        return $this->service;
    }

    public function createAction()
    {
        $params = array('action' => 'create');
        
        $prg = $this->prg($this->url()->fromRoute('pizza/action', $params), true);
    
        if ($prg instanceof Response) {
            return $prg;
    
        } elseif ($prg !== false) {
            $pizza = $this->getPizzaService()->create($prg);
    
            if ($pizza) {
                $params = array('action' => 'update', 'id' => $pizza->getId());
                
                return $this->redirect()->toRoute('pizza/action', $params);
            }
        }
    
        $form = $this->getPizzaService()->getCreateForm();
    
        return array(
            'form' => $form,
        );
    }
}
</pre>
</div>
</div>
