<?php 
/**
 * ZF2 Buch Kapitel 8
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 8.32 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 8.32</h1>
<h3>Beispiel für den Einsatz des <code>FlashMessenger</code> Plugins</h3>
<pre>
&lt;?php
namespace Pizza\Controller;

use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;

class IndexController extends AbstractActionController
{
    public function sendAction()
    {
        $this->flashMessenger()->addMessage('Die Pizza wurde versandt.');
        
        return $this->redirect()->toUrl('/pizza/ordered');
    }
    
    public function orderedAction()
    {
        if ($this->flashMessenger()->hasMessages()) {
            return array('messages' => $this->flashMessenger()->getMessages());
        }
    }
}
</pre>
</div>
</div>
