<?php 
/**
 * ZF2 Buch Kapitel 8
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 8.23 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 8.23</h1>
<h3>RESTful-Controller für Pizza-Service</h3>
<pre>
&lt;?php
namespace Pizza\Controller;

use Pizza\Service\PizzaService;
use Zend\Mvc\Controller\AbstractRestfulController;
use Zend\View\Model\JsonModel;

class RestController extends AbstractRestfulController
{
    protected $service = null;
    
    public function __construct(PizzaService $service)
    {
        $this->setPizzaService($service);
    }
    
    public function setPizzaService(PizzaService $service)
    {
        $this->service = $service;
    }
    
    public function getPizzaService()
    {
        return $this->service;
    }
    
    public function getList()
    {
        return new JsonModel(array(
            'data' => $this->getPizzaService()->fetchList(),
        ));
    }
    
    public function get($id)
    {
        return new JsonModel(array(
            'data' => $this->getPizzaService()->fetchSingleById($id),
        ));
    }
    
    public function create($data)
    {
        $id = $this->getPizzaService()->add($data);

        return $this->get($id);
    }
    
    public function update($id, $data)
    {
        $this->getPizzaService()->update($id, $data);
        
        return $this->get($id);
    }
    
    public function delete($id)
    {
        $this->getPizzaService()->delete($id);
        
        return new JsonModel(array(
            'data' => 'deleted',
        ));
    }
}
</pre>
</div>
</div>
