<?php 
/**
 * ZF2 Buch Kapitel 8
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 8.34 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 8.34</h1>
<h3>Konfiguration der Modul-Klasse für das neue Controller-Plugin</h3>
<pre>
&lt;?php
namespace Pizza;

use Zend\ModuleManager\Feature\ControllerPluginProviderInterface;

class Module implements 
    ControllerPluginProviderInterface
{
    public function getControllerPluginConfig()
    {
        return array(
            'invokables' => array(
                'dump' => 'Pizza\Controller\Plugin\Dump',
            ),
        );
    }
}
</pre>
</div>
</div>
