<?php 
/**
 * ZF2 Buch Kapitel 8
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 8.1 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 8.1</h1>
<h3>Initialisierungsprozess für das Application-Objekt manuell durchführen</h3>
<pre>
&lt;?php
use Zend\Debug\Debug;
use Zend\EventManager\EventManager;
use Zend\Http\PhpEnvironment\Request;
use Zend\Http\PhpEnvironment\Response;
use Zend\ModuleManager\ModuleManager;
use Zend\Mvc\Application;
use Zend\ServiceManager\ServiceManager;

$config = include 'config/application.config.php';

$serviceManager = new ServiceManager();
$serviceManager->setService('ApplicationConfig', $config);
$serviceManager->setService('EventManager', new EventManager());
$serviceManager->setService('ModuleManager', new ModuleManager($config));
$serviceManager->setService('Request', new Request());
$serviceManager->setService('Response', new Response());

$application = new Application($config, $serviceManager);

Debug::dump($serviceManager->getRegisteredServices());
</pre>
<h3>Ausgabe</h3>
<?php 
use Zend\Debug\Debug;
use Zend\EventManager\EventManager;
use Zend\Http\PhpEnvironment\Request;
use Zend\Http\PhpEnvironment\Response;
use Zend\ModuleManager\ModuleManager;
use Zend\Mvc\Application;
use Zend\ServiceManager\ServiceManager;

$config = include LUIGI_ROOT . '/config/application.config.php';

$serviceManager = new ServiceManager();
$serviceManager->setService('ApplicationConfig', $config);
$serviceManager->setService('EventManager', new EventManager());
$serviceManager->setService('ModuleManager', new ModuleManager($config));
$serviceManager->setService('Request', new Request());
$serviceManager->setService('Response', new Response());

$application = new Application($config, $serviceManager);

Debug::dump($serviceManager->getRegisteredServices());
?>
</div>
</div>
