<?php 
/**
 * ZF2 Buch Kapitel 8
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 8.21 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 8.21</h1>
<h3>Modul-Klasse verwendet Factory für Action-Controller</h3>
<pre>
&lt;?php
namespace Pizza;

use Zend\ModuleManager\Feature\ControllerProviderInterface;
use Zend\ModuleManager\Feature\ServiceProviderInterface;

class Module implements 
    ServiceProviderInterface,
    ControllerProviderInterface
{
    public function getServiceConfig()
    {
        return array(
            'invokables' => array(
                'Pizza\Service' => 'Pizza\Service\PizzaService',
            ),
        );
    }
    
    public function getControllerConfig()
    {
        return array(
            'factories' => array(
                'pizza'   => 'Pizza\Controller\IndexControllerFactory',
            ),
        );
    }
}
</pre>
</div>
</div>
