<?php 
/**
 * ZF2 Buch Kapitel 8
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Index view script
 * 
 * @package    Application
 */
?>
<h1>Listings - Kapitel 8</h1>
<table class="table table-bordered table-striped table-hover table-condensed">
<thead>
<tr>
<th>Listing</th>
<th>Beschreibung</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="/listing/listing0801">Listing 8.1</a></td>
<td>Initialisierungsprozess für das Application-Objekt manuell durchführen</td>
</tr>
<tr>
<td><a href="/listing/listing0802">Listing 8.2</a></td>
<td>Initialisierungsprozess für Application mit <code>ServiceManagerConfig</code></td>
</tr>
<tr>
<td><a href="/listing/listing0803">Listing 8.3</a></td>
<td>Bootstrap-Prozess für das Application-Objekt manuell durchführen</td>
</tr>
<tr>
<td><a href="/listing/listing0804">Listing 8.4</a></td>
<td>Verarbeitungsprozess für das Application-Objekt durchführen</td>
</tr>
<tr>
<td><a href="/listing/listing0805">Listing 8.5</a></td>
<td>Beispiel für <code>Hostname</code> Route-Typ</td>
</tr>
<tr>
<td><a href="/listing/listing0806">Listing 8.6</a></td>
<td>Beispiel für <code>Literal</code> Route-Typ</td>
</tr>
<tr>
<td><a href="/listing/listing0807">Listing 8.7</a></td>
<td>Beispiel für <code>Regex</code> Route-Typ</td>
</tr>
<tr>
<td><a href="/listing/listing0808">Listing 8.8</a></td>
<td>Beispiel für <code>Segment</code> Route-Typ</td>
</tr>
<tr>
<td><a href="/listing/listing0809">Listing 8.9</a></td>
<td>Beispiel für <code>SimpleRouteStack</code> Router-Typ</td>
</tr>
<tr>
<td><a href="/listing/listing0810">Listing 8.10</a></td>
<td>Beispiel für <code>TreeRouteStack</code> Router-Typ</td>
</tr>
<tr>
<td><a href="/listing/listing0811">Listing 8.11</a></td>
<td>Konfiguration des <code>TreeRouteStack</code> Router-Typ mit einem Array</td>
</tr>
<tr>
<td><a href="/listing/listing0812">Listing 8.12</a></td>
<td>URLs mit Hilfe von <code>SimpleRouteStack</code> ausgeben</td>
</tr>
<tr>
<td><a href="/listing/listing0813">Listing 8.13</a></td>
<td><code>route</code> Event für die Sprachfestlegung nutzen</td>
</tr>
<tr>
<td><a href="/listing/listing0814">Listing 8.14</a></td>
<td>Listener-Aggregat zum Loggen für <code>dispatch.error</code> Event</td>
</tr>
<tr>
<td><a href="/listing/listing0815">Listing 8.15</a></td>
<td>Modul-Klasse registriert <code>LoggingListener</code></td>
</tr>
<tr>
<td><a href="/listing/listing0816">Listing 8.16</a></td>
<td>Listener-Aggregat zur Laufzeitausgabe für <code>finish</code> Event</td>
</tr>
<tr>
<td><a href="/listing/listing0817">Listing 8.17</a></td>
<td>Modul-Klasse registriert <code>RunTimeListener</code></td>
</tr>
<tr>
<td><a href="/listing/listing0818">Listing 8.18</a></td>
<td>Model-Service für Einsatz im Action-Controller</td>
</tr>
<tr>
<td><a href="/listing/listing0819">Listing 8.19</a></td>
<td>Action-Controller, der den Model-Service einsetzt</td>
</tr>
<tr>
<td><a href="/listing/listing0820">Listing 8.20</a></td>
<td>Factory-Klasse zur Injizierung von Abhängigkeiten für Action-Controller</td>
</tr>
<tr>
<td><a href="/listing/listing0821">Listing 8.21</a></td>
<td>Modul-Klasse verwendet Factory für Action-Controller</td>
</tr>
<tr>
<td><a href="/listing/listing0822">Listing 8.22</a></td>
<td>Action-Controller mit sauberer Dependency Injection</td>
</tr>
<tr>
<td><a href="/listing/listing0823">Listing 8.23</a></td>
<td>RESTful-Controller für Pizza-Service</td>
</tr>
<tr>
<td><a href="/listing/listing0824">Listing 8.24</a></td>
<td>Erweiterter Model-Service für Einsatz im RESTful-Controller</td>
</tr>
<tr>
<td><a href="/listing/listing0825">Listing 8.25</a></td>
<td>Erweiterte Modul-Klasse für Änderung der View-Strategie</td>
</tr>
<tr>
<td><a href="/listing/listing0826">Listing 8.26</a></td>
<td>Routendefinition für RESTful-Controller</td>
</tr>
<tr>
<td><a href="/listing/listing0827">Listing 8.27</a></td>
<td>Testen des RESTful-Controllers mit <code>Zend\Http\Client</code></td>
</tr>
<tr>
<td><a href="/listing/listing0828">Listing 8.28</a></td>
<td>Beispielhafte Routing-Konfiguration für das <code>Url</code> Plugin</td>
</tr>
<tr>
<td><a href="/listing/listing0829">Listing 8.29</a></td>
<td>Beispiel für den Einsatz des <code>Forward</code> Plugins</td>
</tr>
<tr>
<td><a href="/listing/listing0830">Listing 8.30</a></td>
<td>Beispiel für den Einsatz des <code>PostRedirectGet</code> Plugins</td>
</tr>
<tr>
<td><a href="/listing/listing0831">Listing 8.31</a></td>
<td>Beispiel für den Einsatz des <code>FilePostRedirectGet</code> Plugins</td>
</tr>
<tr>
<td><a href="/listing/listing0832">Listing 8.32</a></td>
<td>Beispiel für den Einsatz des <code>FlashMessenger</code> Plugins</td>
</tr>
<tr>
<td><a href="/listing/listing0833">Listing 8.33</a></td>
<td>Eigenes Controller-Plugin zum Dumpen von Variablen</td>
</tr>
<tr>
<td><a href="/listing/listing0834">Listing 8.34</a></td>
<td>Konfiguration der Modul-Klasse für das neue Controller-Plugin</td>
</tr>
</tbody>
</table>
